### ISSUE TITLE
Calibration not working

### ISSUE THREAD

**Issue by patrickhener** [hanneshoettinger/opencv-steel-darts#3]
Hi Hannes,

I have one issue with your code not working for me. So when I run Calibration I will get this:

```
--- darts/hannes-darts ‹master* M› » python2 Calibration_1.py
Welcome to darts!
Traceback (most recent call last):
  File "Calibration_1.py", line 497, in <module>
    calibrate(cam_R, cam_L)
  File "Calibration_1.py", line 450, in calibrate
    calData_R.points = getTransformationPoints(imCal_R, "right")
  File "Calibration_1.py", line 310, in getTransformationPoints
    Ellipse, image_proc_img = findEllipse(thresh2, image_proc_img)
  File "Calibration_1.py", line 166, in findEllipse
    Ellipse.a = a
UnboundLocalError: local variable 'a' referenced before assignment
```

Any idea how to fix this issue?

Also Terminal hangs and `CTRL+C` will not kill the process. Is that intended?

Is there a way to just use the recognition without any game scoring? So let's say I throw and I will get a _Points: 5_ on the cli. And that for any throw I make?

Thanks in advance,
best regards,
Patrick

**Comment by hanneshoettinger** [comment]
That means that during the calibration in 
`findEllipse(thresh2, image_proc_img)`
no ellipse was found and therefore "a" was not set in the loop. 

I have not automated the calibration to automatically adjust thresholds to find allways the correct ellipse or create a user input to handle that case... You have to set the correct threshold for the image processing (black/white, edge detection, ellipse size,...).

Once calibration was successful you can play with `DartsRecognition.py`, where at the cli the dart base score and dart multiplier score of the detected dart is printed. However, you would have to modify the main function to read the calibration data and start afterwards the darts recognition. That would be very good for testing, as shown in the code with a recorded video file.

There are some files of an older version that should be cleaned up, sorry for that. 

`DartsScorer_1.py` is the entry point of the newest version, where you can see which files are imported.

Hope that helps for the start :)

**Comment by patrickhener** [comment]
Well that makes perfect sense, as I did not yet build a compartment and setup a Dart board. So I will come back to this, when I did that. And yes, I guess this repo could surely be cleaned up ;) I suggest moving unused python scripts to a new folder called "archive" or something. This might be the fastest and quickest way to clean up.
Best regards,
Patrick

**Comment by hanneshoettinger** [comment]
You could start checking the code by using one of the videos from the folder `Darts` and test the calibration with only "one camera" first.

**Comment by patrickhener** [comment]
> You could start checking the code by using one of the videos from the folder `Darts` and test the calibration with only "one camera" first.

I am all ears. The possibility to modify code using the recognition with a video would be great right now!
So quick syntax tutorial on how to use your pre-recorded video to test recognition?

**Comment by hanneshoettinger** [comment]
It is implemented in the older version for one camera only: `GetDart.py` and `Calibration.py`. I am not sure right now how different those functions are to the newer version (I have not touched the project for 2 years unfortunately), or if I just packaged them "nicer" into different functions and classes...

Checks if videoCapture device is present, if not, take picture from video:
```
try:
    cam = VideoStream(src=2).start()
    success,imCalRGB = cam.read()
    imCalHSV = cv2.cvtColor(imCalRGB, cv2.COLOR_BGR2HSV)
except:
    vidcap = cv2.VideoCapture("./Darts_Testvideo_9.mp4")
    success,imCalRGB = vidcap.read()
    imCalHSV = cv2.cvtColor(imCalRGB, cv2.COLOR_BGR2HSV)
```

**Comment by patrickhener** [comment]
I noticed that current opencv (versions greater than 2 will not import cv2.cv as .cv is removed from the library entirely). So your code will not work anymore unmodified in current installations.

**Comment by hanneshoettinger** [comment]
Good to know, thanks. Should be no problem to refactor it to work again with a newer version. For now you could use version 2.4.12.

**Comment by patrickhener** [comment]
Okay good to know, but how will I obtain opencv 2.4.12. `pip2 install opencv-python==2.4.12` will fail telling me the least version I can get will be `3.1.0.0`

**Comment by hanneshoettinger** [comment]
You can install it manually from here:
https://opencv.org/releases.html

**Comment by patrickhener** [comment]
:D That will be not that easy as I have to build it from source. I am not developing on windows...

**Comment by hanneshoettinger** [comment]
me neither. I moved to UNIX.
Checkout:
https://docs.opencv.org/2.4/doc/tutorials/introduction/linux_install/linux_install.html

Build from source for raspberry pi also worked with a similar tutorial.

**Comment by hanneshoettinger** [comment]
or you change the code to work with a newer version of opencv, highly welcome ;) I think there should be only some syntax change involved at some parts...

**Comment by patrickhener** [comment]
Compilation will crash cause of newer ffmpeg as it seams. Adapting to newer opencv might be the way to go then. Right now I am on Arch bleeding edge. I will go back to Debian stable system and try again one more time. Otherwise might opt for code changes.

**Comment by hanneshoettinger** [comment]
Thanks for the update. Refactoring to Python3 and Opencv4 would be probably not a bad idea at all :) Some `print` changes and opencv syntax probably only...at the moment I unfortunately do not have the time to help you updating the code base and to clean up the repo. sorry.

**Comment by patrickhener** [comment]
Well I am not a good programmer I would say, but I will try to accomplish this task first. Maybe I'll figure that out ;)

**Comment by patrickhener** [comment]
So today I was able to try out the code (after refactoring it a few times). It seams that the current version only uses one webcam. Isn't it supposed to use both? And also it will not recognize any Darts. It does see the darts and the endless printing of 0 will change to some random numbers. But when running DartsScorer_1.py and press Game On it will just not recognize any Darts.
Is there any trick to it?

**Comment by hanneshoettinger** [comment]
It uses both. If you follow the code in [DartsRecognition](https://github.com/hanneshoettinger/opencv-steel-darts/blob/master/DartsRecognition.py) you see that in the method getDarts, both cameras are used. Is your calibration data stored and loaded while executing the recognition stage?

**Comment by patrickhener** [comment]
How do I determine that it is stored and loaded once again? I have frame1_R and frame1_L jpeg showing the left and the right camera. But in my refactored DartsRecognition script I commented the img and img2 variable in the main loop, cause those images weren't in the repo anymore. Is this the point where the recognition reads the calibration? Do I need to change the path to point to the left and right frame of the calib data? (img = "./frame_L.jpg" for example?)

**Comment by patrickhener** [comment]
Well this is so frustrating. I cannot by any change get it to work. Neither with your old version (python2) now with the one I refactored for python3. And in addition there are two other projects which will not work for me.

**Comment by hanneshoettinger** [comment]
I am sorry to here that. It can be sometimes frustrating, but don't give up :)

If you take a closer look at the calibration routine, you will see that I store the calibration data into:
calibrationData_R.pkl & calibrationData_L.pkl (pickle files). If the data exists in the folder, I will read the calibration data and map it to an overlay, so the user can check if the calibration is still valid. If the user does not agree, the files are removed from disk and you have to re-calibrate. The images are just reference images. So if you start the calibration routine and finish it correctly, you should find the pickle files, with all the calibration information on your disk in the folder of your project. hope that helps.

**Comment by patrickhener** [comment]
That sounds really great and I can understand that just fine. Can you quickly describe how the calibration routine should be done? Like what command do I use? How do I control the windows which are spawned. How does it work? I was not really successful guessing it neither debugging it in code to be honest.

**Comment by patrickhener** [comment]
Hi Hannes, I tried what you were saying but in my case it does not produce any pickle files, as well as the GUI looks somewhat strange. Here have some Pictures:

![frame1_L](https://user-images.githubusercontent.com/7579055/60718511-23847380-9f25-11e9-944e-9206ad3a2f88.jpg)
![frame1_R](https://user-images.githubusercontent.com/7579055/60718514-254e3700-9f25-11e9-8b6d-04d9eabb7fca.jpg)
![20190705_125710](https://user-images.githubusercontent.com/7579055/60718586-529ae500-9f25-11e9-892b-ab901eac55f3.jpg)
![20190705_125734](https://user-images.githubusercontent.com/7579055/60718588-54fd3f00-9f25-11e9-806f-b739ff3def3c.jpg)

How can I debug?/get it to work?

Best regards,
Patrick

**Comment by hanneshoettinger** [comment]
What’s the error in the last image in the console?

Setup looks good.

Patrick Hener <notifications@github.com> schrieb am Fr. 5. Juli 2019 um
13:04:

**Comment by patrickhener** [comment]
The error says:

```
(.venv) --- darts/opencv-steel-darts ‹refactoring› » python Calibration_1.py
Welcome to darts!
error
Traceback (most recent call last):
  File "Calibration_1.py", line 496, in <module>
    calibrate(cam_R, cam_L)
  File "Calibration_1.py", line 450, in calibrate
    cal_data_r.points = get_transformation_points(im_cal_r, "right")
  File "Calibration_1.py", line 318, in get_transformation_points
    angle_zone1 = (ellipse.angle - 5, ellipse.angle + 5)
AttributeError: 'tuple' object has no attribute 'angle'
```

**Comment by omar-ashraf1488** [comment]
Did you find the reason why the calibration did not work? It does not work also by me.

**Comment by patrickhener** [comment]
Never got to that. The project is dead.

**Comment by omar-ashraf1488** [comment]
Do you have another idea to make the calibration?

**Comment by hanneshoettinger** [comment]
you have to play with image thresholds to find the ellipse, if the ellipse is not found, there will be no gui interaction for calibration. probably I will find some time later this year to set this back up and keep working on it. @patrickhener and @omar-ashraf1488 lets shift conversations to: https://www.facebook.com/groups/281778298914107/
